import 'dart:convert';

import 'package:easebuzz_flutter/easebuzz_flutter.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'api_handler.dart';

class easebuzz_integrate extends StatefulWidget {
  const easebuzz_integrate({super.key});

  @override
  State<easebuzz_integrate> createState() => _easebuzz_integrateState();
}

class _easebuzz_integrateState extends State<easebuzz_integrate> {

  bool? Loading = false;


  final _easebuzzFlutterPlugin = EasebuzzFlutter();
  String _paymentResponse = 'No payment response yet';


  Future<void> initiatePayment({String? AccessKey}) async {
    // String accessKey = "Access key generated by the Initiate Payment API";
    String accessKey = AccessKey.toString();
    String payMode = "production"; // Use "production" for live mode
    // String payMode = "test"; // Use "production" for live mode
    try {
      final paymentResponse = await _easebuzzFlutterPlugin.payWithEasebuzz(accessKey,payMode);
      print("paymentResponse -- $paymentResponse");
      setState(() {
        _paymentResponse = "Payment successful: $paymentResponse";
      });
    } on PlatformException catch (e) {
      setState(() {
        _paymentResponse = "Payment failed: ${e.message}";
      });
    }
  }


  var accesskeydata;
  var paymentstatus;



  Payment() async {


    setState(() {
      Loading = true;
    });
    var read = {
      // 'amount': Payable_Amt.toString(),
      'amount': "1",
      'firstname': "test",
      'email': "info@amidharawadi.com",
      'phone': "9662959799",
      // 'phone': LoginMobileNo,
      // 'productinfo': (provider!.get_PersonDetailByRegistrationID!.first.environment=="prod") ? "production" : "test",
      'productinfo': "production",
      // 'productinfo': "test",
      'Txnid': "124686343",
      'Udf1': "",
      'Udf2': "",
      'Udf3': "",
      'Udf4': "",
      'Udf5': "",
      'Udf6': "",
      'Udf7': "",
      'Udf8': "",
      'Udf9': "",
      'Udf10': "",
      'BaseURL': "https://pay.easebuzz.in",
      'PGKey': "3K43L20SR0",
      'PGSalt': "CWWOFZPB7P",
    };

    print("payment");
    await ApiHandler.post(url: "https://webservice.js-team.com/AmidharaRestAPI/api/payment", body: jsonEncode(read))
        .then((value) async {
      if (value.statusCode == 200) {
        var body = value.body.toString();
        var json = jsonDecode(body);
        print("body payment" + body.toString());
        paymentstatus = json["status"];
        accesskeydata = json["data"];

        if (json["message"] == "Successfull") {
          FocusScope.of(context).unfocus();

          initiatePayment(AccessKey: accesskeydata);

        }
        if (json["message"] == "Not generated") {
          FocusScope.of(context).unfocus();
          setState(() {
            Loading = false;
            // PaymentProcess=true;
          });
        }
      } else if (value.statusCode == 404) {
        FocusScope.of(context).unfocus();
        setState(() {
          Loading = false;
          // PaymentProcess=true;
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("easebuzz"),
      ),
      body: Column(
        children: [
          ElevatedButton(
            child: Text("submit"),
            onPressed: (){
              Payment();
            },
          ),
          Text("_paymentResponse --- $_paymentResponse")
        ],
      ),
    );
  }
}
